spring.application.name=nipponhub

spring.datasource.url=jdbc:mysql://localhost:3306/nipponhub_DB
spring.datasource.username=root
spring.datasource.password=

# MongoDB (for images via GridFS)
spring.data.mongodb.uri=mongodb://localhost:27017/nipponhub_files

#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always
spring.main.allow-circular-references=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=50MB

spring.thymeleaf.check-template-location=false

# application.properties
spring.security.user.name=admin
spring.security.user.password=admin

# Change the UI path (optional)
springdoc.swagger-ui.path=/swagger-ui.html

# Change the api-docs path (optional)  
springdoc.api-docs.path=/v3/api-docs

# Useful during dev — shows all endpoints including actuator
springdoc.show-actuator=true

spring.jackson.default-property-inclusion=non_null


# server.port=1010